### ISSUE TITLE
bump release?

### ISSUE THREAD

**Issue by tlambert03** [royerlab/napari-dexp#8]
Hey, all.  Was running tests on all plugins recently and found this one could not be imported after install, due to a missing napari requirement.  I was coming here to suggest that you add napari to your install_requires, since this plugin explicitly imports things from napari.  But I see that you've already done that.  If main is stable, would be good to cut a new release.  thanks!

**Comment by JoOkuma** [comment]
Thanks @tlambert03, I bumped the version and fixed the CI on #11
